title: Vincent Dubois
email: vainzou@gmail.com
description: Personal website of Vincent Dubois
url: https://vincentdubois.fr
intro:
  - title: What
    body: I'm currently working in the logistic department of a fashion brand. Before that I was as a front-end developer and product specialist.
  - title: Where
    body: I live in the lovely Amsterdam for 7 years after studying in France and Switzerland.
  - title: Else
    body: I like to wake-up early to train for triathlons and also baking vegan cakes. 